language: android

branches:
  only:
    - master
    - /v\d+\.\d+[a-z]/

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # The BuildTools version used by your project
    - build-tools-22.0.1

    # The SDK version used to compile your project
    - android-22

notifications:
  email: true

before_install:
  # Disable services enabled by default
  # http://docs.travis-ci.com/user/database-setup/#MySQL
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
  # The following did not work reliable
  # - sudo service mysql stop
  # - sudo service postgresql stop

install:
  # Ensure Gradle wrapper is executable, download wrapper and show version
  - chmod +x ./gradlew; ls -l gradlew; ./gradlew wrapper -v
  # Download and show android dependencies
  # - ./gradlew androidDependencies

#before_script:
#  # Ensure signing configuration is present
#  - mv app/gradle.properties

script:
  - ./gradlew assembleRelease

deploy:
      provider: releases
      api_key: ${api_key}
      file: "app/build/outputs/apk/app-release.apk"
      skip_cleanup: true
      on:
          tags: false
          all_branches: true

deploy_success:
  # CREATE GIT TAG
  - git config --global user.email "jedsada@wisdomlanna.com"
  - git config --global user.name "T-Jedsada"
  - export GIT_TAG=build-$TRAVIS_BRANCH-$(date -u "+%Y-%m-%d")-$TRAVIS_BUILD_NUMBER
  - git commit -m "Set build VERSION number"
  - git tag 1.0.12 -a -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER"
  - git push

branches:
  except:
    - /^*-v[0-9]/


